version: '3.4'

services:

  client:
    build:
      target: base
    command: npm run serve
    volumes:
      - ./services/client/src:/home/node/client/src
      - ./services/client/public:/home/node/client/public
    env_file:
      - ./env_file_development
    environment:
      - NODE_ENV=development

  server:
    build:
      target: development
    command: ./node_modules/.bin/nodemon src
    volumes:
      - ./services/server/src:/home/node/server/src
    env_file:
      - ./env_file_development
    environment:
      - NODE_ENV=development
    links:
      - db
    depends_on:
      - db

  db:
    build:
      context: ./services/db
    command: --default-authentication-plugin=mysql_native_password --general_log=1 --general_log_file=/tmp/query.log
    volumes:
      - ./_data/mysql:/var/lib/mysql
    env_file:
      - ./env_file_development
