version: '3.4'

services:

  client:
    build:
      target: production
      args:
        - NODE_ENV=production
        - HOST_URL=${HOST_URL}
        - STEEM_NETWORK=${STEEM_NETWORK}
        - STEEM_APP_ACCOUNT=${STEEM_APP_ACCOUNT}
        - STEEM_CONNECT_HOST=${STEEM_CONNECT_HOST}
        - STEEM_CONNECT_ACCOUNT=${STEEM_CONNECT_ACCOUNT}
    command: nginx

  server:
    build:
      target: production
    command: node src
    environment:
      - NODE_ENV=production
