version: '3.3'

services:
  db:
    build:
      context: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./_data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tokenbb
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_ONETIME_PASSWORD

