version: '3.4'

services:

  proxy:
    build:
      context: ./services/proxy
    command: wait-for client:8080 -- nginx
    logging:
      driver: none
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - .env
    links:
      - client
      - server
    depends_on:
      - client
      - server

  client:
    build: 
      context: ./services/client
      target: base
    env_file:
      - .env
    expose:
      - "8080"

  server:
    build:
      context: ./services/server
    expose:
      - "8080"
    env_file:
      - .env
