version: '3.4'

services:

  server:
    build:
      context: ./services/server
      target: development
    command: ./node_modules/.bin/nodemon src
    volumes:
      - ./services/server/src:/home/node/server/src
    ports:
      - 127.0.0.1:9090:8080
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    links:
      - db

  db:
    build:
      context: ./services/db
    command: --default-authentication-plugin=mysql_native_password --general_log=1 --general_log_file=/tmp/query.log
    volumes:
      - ./_data/mysql:/var/lib/mysql
    env_file:
      - ./.env
